#!/bin/bash

#| First check to see teensy-loader-cli has been compiled
if [ ! -e teensy-loader-cli/teensy-loader-cli ]; then
	# Compile teensy-loader-cli
	mkdir -p teensy-loader-cli
	cd teensy-loader-cli
	cmake -G "Unix Makefiles" @CMAKE_SOURCE_DIR@/LoadFile
	make
	cd -
fi

#| Loads the hex file onto the teensy
sudo teensy-loader-cli/teensy-loader-cli -mmcu=@MCU@ -w @TARGET_HEX@

exit 0

